version: '3'
services:
  postgres:
    image: postgres:11.12
    environment:
      - POSTGRES_USER=bershka-notify
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=bershka-notify
    ports:
      - 5432:5432
    volumes:
      - ./mount/postgres:/var/lib/postgresql/data/
